/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'


const PadObj = React.forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../pad_music.gltf')
  return (
    <group ref={group && ref} {...props} dispose={null}>
      <mesh material={materials.Pad} geometry={nodes.Pad.geometry} position={[0, 0.37, 0]} />
      <mesh
        material={materials.Keys}
        geometry={nodes.Keys.geometry}
        position={[-0.3, 0.41, -0.41]}
        rotation={[0.16, 0, 0]}
        scale={[0.12, 0.04, 0.11]}
      />
      <mesh
        material={materials.Side}
        geometry={nodes.Side.geometry}
        position={[0.74, 0.16, -0.07]}
        scale={[0.02, 0.07, 0.57]}
      />
    </group>
  )
})

useGLTF.preload('../../pad_music.gltf')

export {PadObj}